image: node:20.10.0

before_script:
  - npm install -g pnpm
  - pnpm install
pages:
  script:
    - pnpm test
    - pnpm build
  artifacts:
    paths:
      - public
  rules:
    # only triggers on main
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
